version: '3.1'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1753
      POSTGRES_DB: postgres
    ports:
      - "5432:5432" 